# Kickoff default config

# Characters shown in front of the query.
prompt = ''

# space between window border and the content in pixel
padding = 100

font = ''  # otf or ttf only
font_size = 32.0

[history]
decrease_interval = 48       # interval to decrease the number of launches

[colors]
# color format: rgb or rgba, if transparency is desired
background = '#282c34aa'
prompt = '#abb2bfff'
text = '#ffffffff'           # for search results
text_query = '#e5c07bff'     # for the search query
text_selected = '#61afefff'  # for the currently selected result
